name: Deploy MultiDocker
on:
  push:
    branches:
      - sample # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t datphits/sample-react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true datphits/sample-react-test npm test

      - run: docker build -t datphits/sample-multi-client ./client
      - run: docker build -t datphits/sample-multi-nginx ./nginx
      - run: docker build -t datphits/sample-multi-server ./server
      - run: docker build -t datphits/sample-multi-worker ./worker

      - run: docker push datphits/sample-multi-client
      - run: docker push datphits/sample-multi-nginx
      - run: docker push datphits/sample-multi-server
      - run: docker push datphits/sample-multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
